// src/components/Block.tsx
import React from 'react'

import { classNameFactory } from '@util'

export const Block = (props?: {
  label: string
  className?: string
  children?: React.ReactNode
}): React.ReactElement => (
  <fieldset className={classNameFactory('block', props?.className)}>
    {props?.label && <legend className='label'>{props.label}</legend>}
    {props?.children}
  </fieldset>
)

// src/components/BlockComponent.vue
<script setup lang="ts">
import classNameFactory from '@/util/classNameFactory'

defineProps<{
  label: string
  className: string
}>()
</script>

<template>
  <fieldset :class="classNameFactory('block', className)">
    <legend class="label" v-if="label">{{ label }}</legend>
    <slot />
  </fieldset>
</template>

<style scoped lang="less">
.block {
  border-style: solid;
  border-width: 1px;
  border-color: var(--foreground-unfocused);
  max-width: 100%;

  > legend.label {
    color: var(--foreground-unfocused);
    user-select: none;
  }

  &:hover {
    border-color: var(--foreground-focused);

    > legend.label {
      color: var(--foreground-focused);
    }
  }
}
</style>
